spring:
  cloud:
    gateway:
      routes:
        - uri: https://albertoimpl.com
          predicates:
            - Path=/sum
          filters:
            - StripPrefix=1
            - SumFilter
server:
  port: 8081