spring:
  cloud:
    gateway:
      routes:
        - uri: https://chicory.dev
          predicates:
            - Path=/sum
          filters:
            - StripPrefix=1
            - SumFilter
        - uri: https://chicory.dev
          predicates:
            - Path=/hello
          filters:
            - StripPrefix=1
            - HelloWorldFilter
server:
  port: 8081